server:
  port: 9000
spring:
  application:
    name: huhu-search-service
  data:
    elasticsearch:
      cluster-nodes: 192.168.170.143:9300
      cluster-name: yeonon

  datasource:
    username: root
    password: 124563
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/
  jpa:
    show-sql: true
  redis:
    host: 47.94.156.44
    port: 6379
    database: 2






